export const ANIMATION = {
  QUEUE_ITEM_ENTER_MS: 300,
  QUEUE_ITEM_LEAVE_MS: 200,
  STATUS_CROSSFADE_MS: 200,
  KPI_TWEEN_MS: 400,
  PROCESSING_PULSE_MS: 1_500,
  FEED_ITEM_ENTER_MS: 300,
  CROSS_PANEL_HIGHLIGHT_MS: 600,
  PROGRESS_BAR_TRANSITION_MS: 300,
} as const
