export function cssMs(ms: number): string {
  return `${ms}ms`
}

export const ANIMATION = {
  QUEUE_ITEM_ENTER_MS: 300,
  QUEUE_ITEM_LEAVE_MS: 200,
  STATUS_CROSSFADE_MS: 200,
  KPI_TWEEN_MS: 400,
  PROCESSING_PULSE_MS: 1_500,
  FEED_ITEM_ENTER_MS: 300,
  CROSS_PANEL_HIGHLIGHT_MS: 600,
  PROGRESS_BAR_TRANSITION_MS: 300,
  CONFETTI_DURATION_MS: 1_500,
  SUCCESS_FLASH_MS: 800,
  CIRCULAR_PROGRESS_TRANSITION_MS: 300,
  SORTABLE_REORDER_MS: 150,
  PROGRESS_SLIDE_MS: 200,
  SCENARIO_CARD_HOVER_MS: 200,
  SCENARIO_CARD_ACTIVE_PULSE_MS: 2_000,
} as const
