import { PANEL_ID } from '@/constants/panels'
import type { PanelId } from '@/constants/panels'
import type { SimulationEventType } from '@/types/simulation'

export const HIGHLIGHT_TARGET = {
  CUSTOMER_STATUS: 'customer-status',
  KPI_COMPLETED_COUNT: 'kpi-completed-count',
  KPI_AVG_WAIT_TIME: 'kpi-avg-wait-time',
  KPI_AVG_PROCESSING_TIME: 'kpi-avg-processing-time',
  KPI_CURRENTLY_WAITING: 'kpi-currently-waiting',
  ACTIVITY_FEED: 'activity-feed',
} as const

export type HighlightTarget = (typeof HIGHLIGHT_TARGET)[keyof typeof HIGHLIGHT_TARGET]

export const TARGET_PANEL: Record<HighlightTarget, PanelId> = {
  [HIGHLIGHT_TARGET.CUSTOMER_STATUS]: PANEL_ID.CUSTOMER,
  [HIGHLIGHT_TARGET.KPI_COMPLETED_COUNT]: PANEL_ID.ANALYTICS,
  [HIGHLIGHT_TARGET.KPI_AVG_WAIT_TIME]: PANEL_ID.ANALYTICS,
  [HIGHLIGHT_TARGET.KPI_AVG_PROCESSING_TIME]: PANEL_ID.ANALYTICS,
  [HIGHLIGHT_TARGET.KPI_CURRENTLY_WAITING]: PANEL_ID.ANALYTICS,
  [HIGHLIGHT_TARGET.ACTIVITY_FEED]: PANEL_ID.ANALYTICS,
}

export const KPI_HIGHLIGHT_MAP: Record<string, HighlightTarget> = {
  'completed-count': HIGHLIGHT_TARGET.KPI_COMPLETED_COUNT,
  'avg-wait-time': HIGHLIGHT_TARGET.KPI_AVG_WAIT_TIME,
  'avg-processing-time': HIGHLIGHT_TARGET.KPI_AVG_PROCESSING_TIME,
  'currently-waiting': HIGHLIGHT_TARGET.KPI_CURRENTLY_WAITING,
}

export const ACTION_HIGHLIGHT_TARGETS: Partial<Record<SimulationEventType, HighlightTarget[]>> = {
  approve: [HIGHLIGHT_TARGET.CUSTOMER_STATUS, HIGHLIGHT_TARGET.KPI_CURRENTLY_WAITING, HIGHLIGHT_TARGET.ACTIVITY_FEED],
  assign: [HIGHLIGHT_TARGET.CUSTOMER_STATUS, HIGHLIGHT_TARGET.KPI_CURRENTLY_WAITING, HIGHLIGHT_TARGET.ACTIVITY_FEED],
  start_processing: [HIGHLIGHT_TARGET.CUSTOMER_STATUS, HIGHLIGHT_TARGET.ACTIVITY_FEED],
  complete: [
    HIGHLIGHT_TARGET.CUSTOMER_STATUS,
    HIGHLIGHT_TARGET.KPI_COMPLETED_COUNT,
    HIGHLIGHT_TARGET.KPI_AVG_PROCESSING_TIME,
    HIGHLIGHT_TARGET.KPI_AVG_WAIT_TIME,
    HIGHLIGHT_TARGET.ACTIVITY_FEED,
  ],
}
